# Generated by Django 2.0 on 2018-11-10 09:51

from django.db import migrations, models
import djgeojson.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MushroomSpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('num', models.IntegerField(default='0')),
                ('description', models.TextField()),
                ('picture', models.CharField(default='', max_length=100)),
                ('color', models.CharField(default='#ff7800', max_length=20)),
                ('geom', djgeojson.fields.PolygonField()),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('num', models.IntegerField(default='0')),
                ('description', models.TextField()),
                ('picture', models.ImageField(blank=True, upload_to='')),
                ('icon', models.TextField(default='')),
                ('geom', djgeojson.fields.PointField()),
            ],
        ),
    ]
