# Generated by Django 2.0 on 2019-01-12 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djgeojson.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('level', models.IntegerField(default='1')),
                ('description', models.TextField()),
                ('picture', models.CharField(default='', max_length=100)),
                ('icon', models.TextField(default='')),
                ('geom', djgeojson.fields.PointField()),
            ],
        ),
        migrations.CreateModel(
            name='Polygon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('level', models.IntegerField(default='1')),
                ('description', models.TextField()),
                ('picture', models.CharField(default='', max_length=100)),
                ('color', models.CharField(default='#ff7800', max_length=20)),
                ('geom', djgeojson.fields.PolygonField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id1', models.IntegerField(default='1')),
                ('id2', models.IntegerField(default='1')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('price', models.IntegerField(default=0)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='polygon',
            name='quest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.Quest'),
        ),
        migrations.AddField(
            model_name='marker',
            name='quest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.Quest'),
        ),
    ]
