# Generated by Django 2.0 on 2018-11-12 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_auto_20181112_1450'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MSecond_Quest_Polygon',
            new_name='Second_Quest_Polygon',
        ),
    ]
