# Generated by Django 2.0 on 2018-11-12 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_auto_20181112_1451'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MushroomSpot',
            new_name='FirstQuestPolygon',
        ),
    ]
