# Generated by Django 2.0 on 2018-11-12 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_auto_20181112_1453'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FirstQuestPolygon',
            new_name='First_Quest_Polygon',
        ),
    ]
