# Generated by Django 2.0 on 2018-11-12 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_auto_20181112_1454'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Point',
            new_name='First_Quest_Marker',
        ),
    ]
