# Generated by Django 2.0 on 2018-11-12 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_auto_20181112_1456'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Second_Quest_Marker',
            new_name='FirstQuestMarker',
        ),
        migrations.RenameModel(
            old_name='First_Quest_Polygon',
            new_name='FirstQuestPolygon',
        ),
        migrations.RenameModel(
            old_name='First_Quest_Marker',
            new_name='SecondQuestMarker',
        ),
        migrations.RenameModel(
            old_name='Second_Quest_Polygon',
            new_name='SecondQuestPolygon',
        ),
    ]
