# Generated by Django 2.0 on 2018-11-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_auto_20181112_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_quest',
            field=models.IntegerField(default='1'),
        ),
    ]
