# Generated by Django 2.0 on 2018-11-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0009_auto_20181112_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstquestmarker',
            name='level',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='firstquestpolygon',
            name='level',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='secondquestmarker',
            name='level',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='secondquestpolygon',
            name='level',
            field=models.IntegerField(default='1'),
        ),
    ]
