# Generated by Django 2.0 on 2018-11-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0010_auto_20181112_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='second_quest',
            field=models.IntegerField(default='1'),
        ),
    ]
