# Generated by Django 2.0 on 2018-11-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0011_profile_second_quest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
            ],
        ),
    ]
