# Generated by Django 2.0 on 2018-11-12 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0012_quest'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstquestpolygon',
            name='quest',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='map.Quest'),
        ),
    ]
