# Generated by Django 2.0 on 2018-11-12 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0013_firstquestpolygon_quest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstquestpolygon',
            name='quest',
            field=models.ForeignKey(default='Ola', null=True, on_delete=django.db.models.deletion.CASCADE, to='map.Quest'),
        ),
    ]
