# Generated by Django 2.0 on 2018-12-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0016_auto_20181112_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstquestmarker',
            name='picture',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='secondquestmarker',
            name='picture',
            field=models.CharField(default='', max_length=100),
        ),
    ]
