# Generated by Django 2.0 on 2018-12-08 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0017_auto_20181208_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firstquestpolygon',
            name='quest',
        ),
        migrations.DeleteModel(
            name='Quest',
        ),
    ]
