# Generated by Django 2.0 on 2018-12-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0018_auto_20181208_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('city_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
            ],
        ),
    ]
