# Generated by Django 2.0 on 2018-12-16 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0019_quest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quest',
            old_name='city_id',
            new_name='quest_id',
        ),
    ]
