# Generated by Django 2.0 on 2018-12-16 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0020_auto_20181216_1051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quest',
            old_name='quest_id',
            new_name='id',
        ),
    ]
