# Generated by Django 2.0 on 2018-12-16 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0021_auto_20181216_1052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='first_quest',
            new_name='id1',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='second_quest',
            new_name='id2',
        ),
    ]
