# Generated by Django 2.0 on 2018-12-16 12:56

from django.db import migrations, models
import django.db.models.deletion
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0022_auto_20181216_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Polygon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('level', models.IntegerField(default='1')),
                ('description', models.TextField()),
                ('picture', models.CharField(default='', max_length=100)),
                ('color', models.CharField(default='#ff7800', max_length=20)),
                ('geom', djgeojson.fields.PolygonField()),
            ],
        ),
        migrations.AddField(
            model_name='quest',
            name='polygons',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='map.Polygon'),
            preserve_default=False,
        ),
    ]
