# Generated by Django 2.0 on 2018-12-16 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0023_auto_20181216_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quest',
            name='polygons',
        ),
        migrations.AddField(
            model_name='polygon',
            name='quest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='map.Quest'),
            preserve_default=False,
        ),
    ]
