# Generated by Django 2.0 on 2018-12-16 15:13

from django.db import migrations, models
import django.db.models.deletion
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0024_auto_20181216_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('level', models.IntegerField(default='1')),
                ('description', models.TextField()),
                ('picture', models.CharField(default='', max_length=100)),
                ('icon', models.TextField(default='')),
                ('geom', djgeojson.fields.PointField()),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.Quest')),
            ],
        ),
    ]
