# Generated by Django 2.0 on 2018-12-22 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0025_marker'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FirstQuestMarker',
        ),
        migrations.DeleteModel(
            name='FirstQuestPolygon',
        ),
        migrations.DeleteModel(
            name='SecondQuestMarker',
        ),
        migrations.DeleteModel(
            name='SecondQuestPolygon',
        ),
    ]
