# Generated by Django 2.0 on 2018-12-25 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0027_quest_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
